name:                bioseq
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/bioseq#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - bytestring

library:
  exposed-modules:
     - Bio.BioSeq
     - Bio.BioSeq.DNASeq
     - Bio.BioSeq.DNASeq.TypeNats
  source-dirs: lib
